tap "anomalyco/tap", trusted: true
tap "oven-sh/bun", trusted: true
tap "stripe/stripe-cli", trusted: true
tap "tw93/tap", trusted: true
brew "agent-browser"
brew "bun"
brew "cloudflared"
brew "ffmpeg"
brew "fnm"
brew "fzf"
brew "gh"
brew "googleworkspace-cli"
brew "lazygit"
brew "mupdf"
brew "rust"
brew "tmux"
brew "tree"
brew "yt-dlp"
brew "zsh-autosuggestions"
brew "anomalyco/tap/opencode", trusted: true
brew "stripe/stripe-cli/stripe"
brew "tw93/tap/mole"
cask "anki"
cask "beekeeper-studio"
cask "codex-app"
cask "discord"
cask "gcloud-cli"
cask "google-chrome"
cask "granola"
cask "kitlangton-hex"
cask "miniconda"
cask "obsidian"
cask "raycast"
cask "slack"
cask "spotify"
cask "tailscale-app"
cargo "terminal-control"
cask "wispr-flow"
cask "zed"
npm "corepack"
npm "executor"
npm "skills"
